
import {
  Amp, CompressionType, BaseEncode
} from './amp';

import {
  Deamp
} from './deamp';

declare function require(m: string): any;
const fs = require('fs').promises;
const path = require('path');
declare const __dirname: string;

let files = [
  "Bids.csv", 
  "TitanicSurvival.csv", 
  "chickweed.csv", 
  "edcT.csv", 
  "mecter.csv", 
  "treering.csv", 
];

let fileStrings = [] as string[];

declare const Buffer: any;

beforeAll(async () => {
  for (let f of files) {
    let fileContents = await fs.readFile(path.resolve(__dirname, 'testData', f));
    fileStrings.push(fileContents.toString());
  }
});
let testFile = `bib,time in,time out
1,01:05,01:55
2,01:05,01:55
3,01:05,01:55
4,01:05,01:55
5,01:05,01:55
6,01:05,01:55
7,01:05,01:55
8,01:05,01:55
9,01:05,01:55
10,01:05,01:55
11,01:05,01:55
12,01:05,01:55
13,01:05,01:55
14,01:05,01:55`;

test("Simple file amp and deamp", () => {
  let amp = new Amp({
    blkSize: 64,
    compression: CompressionType.LZMA, // Should be ignored, the file is too small
    filename: "testFile.txt",
    fileModifiedTime: new Date(),
    inputBuffer: testFile,
    skipProgram: true,
    useEOF: false,
    useEOT: false,
  });

  expect(amp).toBeTruthy();

  let blockCount  = amp.getDataBlockCount();
  let blocksToXmit = [...Array(blockCount).keys()].map(n=>n+1);
  blocksToXmit.sort(() => Math.random() - 0.5);

  let fileAmpString = amp.toString(blocksToXmit);

  let deamp = new Deamp();
  const onNewFileFn = jest.fn();
  const onFileUpdateFn = jest.fn();
  const onFileCompleteFn = jest.fn();
  deamp.newFileEvent.on(onNewFileFn);
  deamp.fileUpdateEvent.on(onFileUpdateFn);
  deamp.fileCompleteEvent.on(onFileCompleteFn);

  deamp.ingestString(fileAmpString);
  let fileHash = amp.hash;

  expect(onNewFileFn).toHaveBeenCalledTimes(1);
  expect(onFileUpdateFn).toHaveBeenCalledTimes(6);
  expect(onFileCompleteFn).toHaveBeenCalledTimes(1);
  expect(onFileUpdateFn).toHaveBeenCalledWith({
    blockCount: 4,
    blockSize: 64,
    blocksNeeded: [],
    blocksSeen: [1, 2, 3, 4],
    filename: "testFile.txt",
    hash: fileHash,
  });

  let outFile = deamp.getFile(fileHash);

  expect(outFile.getContent()).toEqual(testFile);
});

test("Decodes a C++ FLAMP compressed base64 transmission", () => {
  // This is a real-world transmission generated by the C++ FLAMP reference
  // implementation. It uses the FLAMP LZMA payload layout:
  //   \\u0001LZMA [original length: 4 bytes LE] [props: 5 bytes] [compressed data]
  // which differs from the raw lzma-js LZMA-Alone layout. Before the format
  // conversion fix this payload failed with "corrupted input".
  const transmission = `
<FILE 34 8C1F>{1279}20260613154011:Station-0.txt
<SIZE 16 500D>{1279}1365 11 64
<DATA 72 4720>{1279:1}[b64:start]AUxaTUFVBQAAXQAAAAQAPYiIp0QD8Lr6nObkwN64MxVeb406FB90W
<DATA 72 2577>{1279:2}tBRfERl6wtBL7bkLx3vOEEoHMYmcgByyAu4mqrywIKNisZGkCG6BbGL/hHc4GvYF
<DATA 72 C691>{1279:3}21oXEnSnKuwMPvHMh4d5/KvBDPtELfqvI89cPc/32cxNc1dOMMW0TZkMswRRhdtz
<DATA 72 CC51>{1279:4}A0u/YTVql4xjp60IKVBgIsk+yDWlw1wCYyFlMfeXxIxZtmEXHN2tQWleEkmcLbBK
<DATA 72 FD72>{1279:5}kmsOcVi/TpC2UR6Ad9A5hyTtc4BKjATdwfeaqvgErJ2XrKqswoUBMeqrffqbAB+i
<DATA 72 F5EA>{1279:6}3M6z319J8nWXoH/IImNRwXz9mN4N6RxvtkqeHGuYV6Cs+ON/EeFXuvNr8y4RjTyF
<DATA 72 5D40>{1279:7}tPhy9GFAbnjM0sTtwfQr0lOPHiIzSb9H9QT9ON1R3X+m8Aep3zjRQLfuUunu1qa/
<DATA 72 5A14>{1279:8}epaiDBF3JIZuJhzX2qzxgeGCeIjRRhLJ0KzLA5gJXdHkfVD5RZVzJ4IbXcr2u12l
<DATA 72 4A39>{1279:9}Bz33+HzvvnAGIN198EAWgH4j81dOAMr6LYyr6yo4Gg5pasUoxBFykWCxmDB19iXo
<DATA 73 A2B5>{1279:10}gyhqYMN7JitOwKXmQhTzgL8W1BRLHeNTVLCgJE1YOJpkDd2nUUnyrMbbpkSjkUB3
<DATA 29 3BBD>{1279:11}nami/ICM7sA[b64:end]`;

  const deamp = new Deamp();
  deamp.ingestString(transmission);

  const file = deamp.getFile('1279');
  expect(file).toBeTruthy();
  const content = file.getContent();
  expect(content).toHaveLength(1365);
  expect(content!.startsWith('{"epoch":29689140}')).toBe(true);
});

test("Compressed base91 file amp and deamp", () => {
  let amp = new Amp({
    blkSize: 64,
    compression: CompressionType.LZMA, // Should be ignored, the file is too small
    forceCompress: true,
    base: BaseEncode.b91,
    filename: "testFile.txt",
    fileModifiedTime: new Date(),
    inputBuffer: testFile,
    skipProgram: true,
    useEOF: false,
    useEOT: false,
  });

  expect(amp).toBeTruthy();

  let blockCount  = amp.getDataBlockCount();
  let blocksToXmit = [...Array(blockCount).keys()].map(n=>n+1);
  blocksToXmit.sort(() => Math.random() - 0.5);

  let fileAmpString = amp.toString(blocksToXmit);

  let deamp = new Deamp();
  const onNewFileFn = jest.fn();
  const onFileUpdateFn = jest.fn();
  const onFileCompleteFn = jest.fn();
  deamp.newFileEvent.on(onNewFileFn);
  deamp.fileUpdateEvent.on(onFileUpdateFn);
  deamp.fileCompleteEvent.on(onFileCompleteFn);

  deamp.ingestString(fileAmpString);
  let fileHash = amp.hash;

  expect(onNewFileFn).toHaveBeenCalledTimes(1);
  expect(onFileCompleteFn).toHaveBeenCalledTimes(1);
  expect(onFileUpdateFn).toHaveBeenCalledTimes(blockCount + 2);
  expect(onFileUpdateFn).toHaveBeenLastCalledWith({
    blockCount: blockCount,
    blockSize: 64,
    blocksNeeded: [],
    blocksSeen: blocksToXmit.sort((a, b) => a - b),
    filename: "testFile.txt",
    hash: fileHash,
  });
  expect(onFileCompleteFn).toHaveBeenCalledTimes(1);

  let outFile = deamp.getFile(fileHash);

  expect(outFile.getContent()).toEqual(testFile);
});

xtest("Large file amp uncompressed then deamp", () => {
  let fileNo = 3;
  let curFile = fileStrings[fileNo]; // large file
  let blockSize = 64;

  let amp = new Amp({
    blkSize: blockSize,
    compression: false, // Should be ignored, the file is too small
    filename: files[fileNo],
    fileModifiedTime: new Date(),
    inputBuffer: curFile,
    skipProgram: true,
    useEOF: false,
    useEOT: false,
    base: BaseEncode.b91
  });

  let blockCount  = amp.getDataBlockCount();
  expect(blockCount).toBe(Math.ceil(curFile.length / blockSize));
  let blocksToXmit = [...Array(blockCount).keys()].map(n=>n+1);
  // shuffle the block order to make sure out-of-order receive works
  blocksToXmit.sort(() => Math.random() - 0.5);

  let fileAmpString = amp.toString(blocksToXmit);

  let deamp = new Deamp();
  const onNewFileFn = jest.fn();
  const onFileUpdateFn = jest.fn();
  const onFileCompleteFn = jest.fn();
  deamp.newFileEvent.on(onNewFileFn);
  deamp.fileUpdateEvent.on(onFileUpdateFn);
  deamp.fileCompleteEvent.on(onFileCompleteFn);

  deamp.ingestString(fileAmpString);
  let fileHash = amp.hash;

  expect(onNewFileFn).toHaveBeenCalledTimes(1);
  expect(onFileCompleteFn).toHaveBeenCalledTimes(1);
  expect(onFileUpdateFn).toHaveBeenLastCalledWith({
    blockCount: blockCount,
    blockSize: blockSize,
    blocksNeeded: [],
    blocksSeen: blocksToXmit.sort((a, b) => a - b),
    filename: files[fileNo],
    hash: fileHash,
  });

  let outFile = deamp.getFile(fileHash);

  expect(outFile.getContent()).toEqual(curFile);
});

xtest("Large file amp compressed then deamp", () => {
  let fileNo = 3;
  let curFile = fileStrings[fileNo]; // large file
  let blockSize = 64;

  let amp = new Amp({
    blkSize: blockSize,
    compression: CompressionType.LZMA, // Should be ignored, the file is too small
    filename: files[fileNo],
    fileModifiedTime: new Date(),
    inputBuffer: curFile,
    skipProgram: true,
    useEOF: false,
    useEOT: false,
    base: BaseEncode.b64
  });

  let blockCount  = amp.getDataBlockCount();
  // Without compression this is how big it would be
  expect(blockCount).toBeLessThan(Math.ceil(curFile.length / blockSize));
  let blocksToXmit = [...Array(blockCount).keys()].map(n=>n+1);
  // shuffle the block order to make sure out-of-order receive works
  blocksToXmit.sort(() => Math.random() - 0.5);

  let fileAmpString = amp.toString(blocksToXmit);

  let deamp = new Deamp();
  const onNewFileFn = jest.fn();
  const onFileUpdateFn = jest.fn();
  const onFileCompleteFn = jest.fn();
  deamp.newFileEvent.on(onNewFileFn);
  deamp.fileUpdateEvent.on(onFileUpdateFn);
  deamp.fileCompleteEvent.on(onFileCompleteFn);

  deamp.ingestString(fileAmpString);
  let fileHash = amp.hash;

  expect(onNewFileFn).toHaveBeenCalledTimes(1);
  expect(onFileCompleteFn).toHaveBeenCalledTimes(1);
  expect(onFileUpdateFn).toHaveBeenLastCalledWith({
    blockCount: blockCount,
    blockSize: blockSize,
    blocksNeeded: [],
    blocksSeen: blocksToXmit.sort((a, b) => a - b),
    filename: files[fileNo],
    hash: fileHash,
  });

  let outFile = deamp.getFile(fileHash);

  expect(outFile.getContent()).toEqual(curFile);
});